name: ng2_form_components
description: Angular 2 stateful form components
version: 0.1.3
environment:
  sdk: '>=2.0.0-dev.62.0 <3.0.0'
dependencies:
  angular: ^5.0.0-beta+2
  rxdart: ^0.18.1
  tuple: ^1.0.0
  dorm: ^1.0.37
  ng2_state:
    git: git@github.com:frankpepermans/ng2_state.git
dev_dependencies:
  built_dorm:
    git: git@github.com:frankpepermans/built_dorm.git
  test: ^1.3.0
  build: ^0.12.7
  source_gen: ^0.8.3
  build_runner: ^0.9.2
  build_test: ^0.10.3
  build_web_compilers: ^0.4.1
  faker: ^0.0.5
web:
  compiler:
    debug: dartdevc
