name: ng2_form_components
description: Angular 2 stateful form components
version: 0.1.3
environment:
  sdk: '>=1.21.0 <2.0.0'
dependencies:
  angular: ^5.0.0-alpha+11
  rxdart: ^0.16.0
  tuple: ^1.0.0
  dorm: ^1.0.37
  ng2_state:
    git: git@github.com:frankpepermans/ng2_state.git
dev_dependencies:
  build: ^0.12.0
  source_gen: ^0.8.0
  build_runner: ^0.8.7
  build_test: ^0.10.0
  build_web_compilers: ^0.3.7
  faker: ^0.0.5
dependency_overrides:
  ng2_state:
    path: ../ng2_state
web:
  compiler:
    debug: dartdevc
