name: ng2_form_components
description: Angular 2 stateful form components
version: 0.0.97
environment:
  sdk: '>=1.21.0 <2.0.0'
dependencies:
  analyzer: ^0.29.1
  angular2: ^2.0.0-beta.18
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^0.1.0
  rxdart: any
  tuple: any
  dorm: any
  ng2_state:
    git: git@github.com:frankpepermans/ng2_state.git
dev_dependencies:
  build_runner: '>=0.1.0'
  source_gen: '>=0.5.0'
  faker: any
dependency_overrides:
  build: '^0.6.0'
transformers:
  - angular2:
      platform_directives:
      - 'package:angular2/common.dart#COMMON_DIRECTIVES'
      platform_pipes:
      - 'package:angular2/common.dart#COMMON_PIPES'
      entry_points: web/main.dart
  - angular2/transform/reflection_remover:
      $include:
        - web/main.dart
        - web/orm_init.dart
        - lib/src/src/common/common_directives.dart
  - dart_to_js_script_rewriter
