name: ng2_form_components
description: Angular 2 stateful form components
version: 0.0.98
environment:
  sdk: '>=1.21.0 <2.0.0'
dependencies:
  analyzer: ^0.29.1
  angular2: 3.1.0
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^0.1.0
  rxdart: 0.9.0
  tuple: any
  dorm: any
  ng2_state:
    git: git@github.com:frankpepermans/ng2_state.git
dev_dependencies:
  build_runner: '>=0.1.0'
  source_gen: '>=0.5.0'
  faker: any
dependency_overrides:
  build: '^0.7.0'
transformers:
  - angular2:
      use_legacy_style_encapsulation: true
      platform_directives:
      - 'package:angular2/common.dart#COMMON_DIRECTIVES'
      platform_pipes:
      - 'package:angular2/common.dart#COMMON_PIPES'
      entry_points: web/main.dart
  - angular2/transform/reflection_remover:
      $include:
        - lib/src/components/auto_complete.dart
        - lib/src/components/drop_down.dart
        - lib/src/components/form_input.dart
        - lib/src/components/hierarchy.dart
        - lib/src/components/html_text_transform_component.dart
        - lib/src/components/html_text_transform_menu.dart
        - lib/src/components/list_renderer.dart
        - lib/src/components/side_panel.dart
        - lib/src/components/text_input.dart
        - lib/src/components/toaster.dart
        - lib/src/components/window_container.dart
  - $dart2js:
      checked: false
      minify: true
      commandLineOptions: ['--trust-type-annotations', '--trust-primitives', '--show-package-warnings', '--enable-diagnostic-colors']
  - dart_to_js_script_rewriter
