name: ng2_form_components
description: Angular 2 stateful form components
version: 0.1.0
environment:
  sdk: '>=1.21.0 <2.0.0'
dependencies:
  analyzer: '>=0.29.10 <0.31.0'
  angular: ^4.0.0
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1
  rxdart: ^0.14.0
  tuple: ^1.0.0
  dorm: ^1.0.37
  ng2_state:
    git: git@github.com:frankpepermans/ng2_state.git
dev_dependencies:
  build_runner: ^0.5.0
  source_gen: ^0.7.0
  faker: ^0.0.5
dependency_overrides:
  ng2_state:
    path: ../ng2_state
  dorm:
    path: ../dorm
transformers:
  - angular:
      use_legacy_style_encapsulation: true
      entry_points: web/main.dart
  - angular/transform/reflection_remover:
      $include:
        - lib/src/components/auto_complete.dart
        - lib/src/components/drop_down.dart
        - lib/src/components/form_input.dart
        - lib/src/components/hierarchy.dart
        - lib/src/components/html_text_transform_component.dart
        - lib/src/components/html_text_transform_menu.dart
        - lib/src/components/list_renderer.dart
        - lib/src/components/side_panel.dart
        - lib/src/components/text_input.dart
        - lib/src/components/toaster.dart
        - lib/src/components/window_container.dart
  - $dart2js:
      checked: false
      minify: true
      commandLineOptions: ['--trust-type-annotations', '--trust-primitives', '--show-package-warnings', '--enable-diagnostic-colors']
  - dart_to_js_script_rewriter
